//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeweb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GAMAOTOWEBEntities : DbContext
    {
        public GAMAOTOWEBEntities()
            : base("name=GAMAOTOWEBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Randevular> Randevular { get; set; }
        public DbSet<Tbl_Hizmetler> Tbl_Hizmetler { get; set; }
        public DbSet<Tbl_Teknisyenler> Tbl_Teknisyenler { get; set; }
        public DbSet<Tbl_Yorumlar> Tbl_Yorumlar { get; set; }
        public DbSet<Tbl_Mesajlar> Tbl_Mesajlar { get; set; }
        public DbSet<Tbl_Resimler> Tbl_Resimler { get; set; }
        public DbSet<Tbl_Ayarlar> Tbl_Ayarlar { get; set; }
        public DbSet<Tbl_Uyeler> Tbl_Uyeler { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tbl_SSS> Tbl_SSS { get; set; }
        public DbSet<Tbl_Duyurular> Tbl_Duyurular { get; set; }
        public DbSet<Tbl_DuyuruYorumlar> Tbl_DuyuruYorumlar { get; set; }
        public DbSet<Tbl_Admin> Tbl_Admin { get; set; }
    }
}
