//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevular
    {
        public int RandevuID { get; set; }
        public string MusteriAdSoyad { get; set; }
        public string MusteriEmail { get; set; }
        public string HizmetTuru { get; set; }
        public Nullable<System.DateTime> RandevuTarihi { get; set; }
        public string OzelTalep { get; set; }
        public string Durum { get; set; }
        public Nullable<int> UyeID { get; set; }
    }
}
