//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Teknisyenler
    {
        public int TeknisyenID { get; set; }
        public string AdSoyad { get; set; }
        public string Gorev { get; set; }
        public string ResimYolu { get; set; }
        public string FacebookUrl { get; set; }
        public string TwitterUrl { get; set; }
        public string InstagramUrl { get; set; }
    }
}
