//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SSS
    {
        public int ID { get; set; }
        public string Soru { get; set; }
        public string Cevap { get; set; }
        public Nullable<int> Sira { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
