//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Yorumlar
    {
        public int YorumID { get; set; }
        public string MusteriAdSoyad { get; set; }
        public string Meslek { get; set; }
        public string YorumMetni { get; set; }
        public string MusteriResim { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<int> UyeID { get; set; }
        public Nullable<System.DateTime> YorumTarihi { get; set; }
        public Nullable<int> Puan { get; set; }
    
        public virtual Tbl_Uyeler Tbl_Uyeler { get; set; }
    }
}
