//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Uyeler
    {
        public Tbl_Uyeler()
        {
            this.Tbl_Yorumlar = new HashSet<Tbl_Yorumlar>();
            this.Tbl_Duyurular = new HashSet<Tbl_Duyurular>();
            this.Tbl_DuyuruYorumlar = new HashSet<Tbl_DuyuruYorumlar>();
        }
    
        public int UyeID { get; set; }
        public string AdSoyad { get; set; }
        public string Email { get; set; }
        public string Sifre { get; set; }
        public string UyeResim { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    
        public virtual ICollection<Tbl_Yorumlar> Tbl_Yorumlar { get; set; }
        public virtual ICollection<Tbl_Duyurular> Tbl_Duyurular { get; set; }
        public virtual ICollection<Tbl_DuyuruYorumlar> Tbl_DuyuruYorumlar { get; set; }
    }
}
