//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Duyurular
    {
        public Tbl_Duyurular()
        {
            this.Tbl_DuyuruYorumlar = new HashSet<Tbl_DuyuruYorumlar>();
        }
    
        public int DuyuruID { get; set; }
        public string Baslik { get; set; }
        public string DuyuruMetni { get; set; }
        public string ResimYolu { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> Goruntulenme { get; set; }
        public Nullable<int> BegeniSayisi { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<int> UyeID { get; set; }
    
        public virtual ICollection<Tbl_DuyuruYorumlar> Tbl_DuyuruYorumlar { get; set; }
        public virtual Tbl_Uyeler Tbl_Uyeler { get; set; }
    }
}
