//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DuyuruYorumlar
    {
        public int YorumID { get; set; }
        public Nullable<int> DuyuruID { get; set; }
        public string AdSoyad { get; set; }
        public string YorumMetni { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<int> UyeID { get; set; }
    
        public virtual Tbl_Duyurular Tbl_Duyurular { get; set; }
        public virtual Tbl_Uyeler Tbl_Uyeler { get; set; }
    }
}
