//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Resimler
    {
        public int SliderID { get; set; }
        public string UstBaslik { get; set; }
        public string Baslik { get; set; }
        public string ArkaPlanResim { get; set; }
        public string OnResim { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
